parameters:
  repoName: self
  azureSubscription: ''
  storage: ''
  containerName: ''

jobs:
- deployment: DeployApp
  displayName: Deploy Console
  pool:
    vmImage: 'windows-latest'
  environment: dev
  strategy: 
    runOnce:
      deploy:
        steps:
          - script: echo my first deployment

          - task: AzureFileCopy@3
            inputs:
              SourcePath: '$(Pipeline.Workspace)'
              azureSubscription: '${{ parameters.azureSubscription }}'
              Destination: 'AzureBlob'
              storage: '${{ parameters.storage }}'
              ContainerName: '${{ parameters.containerName }}'