parameters:
  repoName: self
  azureSubscription: 'Visual Studio Enterprise – MPN(93ddb8b3-ddb9-4d1c-ba59-421456e65538)'
  storage: ''
  containerName: ''

jobs:
- deployment: DeployApp
  dependsOn:
  - build
  - test
  displayName: Deploy App to Storage Account
  pool:
    vmImage: 'windows-latest'
  environment: dev
  strategy: 
    runOnce:
      deploy:
        steps:
          - script: echo my first deployment

          - task: AzureFileCopy@3
            inputs:
              SourcePath: '$(Pipeline.Workspace)'
              azureSubscription: 'Visual Studio Enterprise – MPN(93ddb8b3-ddb9-4d1c-ba59-421456e65538)'
              Destination: 'AzureBlob'
              storage: '{{ parameters.storage }}'
              ContainerName: '{{ parameters.containerName }}'