parameters:
  azureSubscription: '' # Required
  authenticationType: 'server' # Options: server, aadAuthenticationPassword, aadAuthenticationIntegrated, connectionString, servicePrincipal
  serverName: '' # Required when authenticationType == Server || AuthenticationType == AadAuthenticationPassword || AuthenticationType == AadAuthenticationIntegrated || AuthenticationType == servicePrincipal
  databaseName: '' # Required when authenticationType == Server || AuthenticationType == AadAuthenticationPassword || AuthenticationType == AadAuthenticationIntegrated || AuthenticationType == servicePrincipal
  sqlUsername: '' # Required when authenticationType == Server
  sqlPassword: '' # Required when authenticationType == Server
  aadSqlUsername: '' # Required when authenticationType == AadAuthenticationPassword
  aadSqlPassword: '' # Required when authenticationType == AadAuthenticationPassword
  connectionString: '' # Required when authenticationType == ConnectionString
  publishProfile: '' # Optional
  additionalArguments: '' # Optional
  environment: ''
  pool: 
    vmImage: 'windows-latest'

jobs:
- deployment: deploy_db
  displayName: Deploy Database
  workspace:
    clean: all

  environment: '${{ parameters.environment }}'

  strategy:
    runOnce:
      deploy:
        steps:

        # get .dacpac file path
        - powershell: |
            Get-ChildItem "$(Pipeline.Workspace)\${{ parameters.appName.name }}" -Filter *.dacpac | 
            Foreach-Object {
                Write-Host "##vso[task.setvariable variable=dacpacFilePath;]$($_.FullName)"
            }
          displayName: dacpac file path

        - task: SqlAzureDacpacDeployment@1
          inputs:
            azureSubscription: ${{ parameters.azureSubscription }}
            authenticationType: ${{ parameters.authenticationType }}
            serverName: ${{ parameters.serverName }} # Required when authenticationType == Server || AuthenticationType == AadAuthenticationPassword || AuthenticationType == AadAuthenticationIntegrated || AuthenticationType == servicePrincipal
            databaseName: ${{ parameters.databaseName }} # Required when authenticationType == Server || AuthenticationType == AadAuthenticationPassword || AuthenticationType == AadAuthenticationIntegrated || AuthenticationType == servicePrincipal
            sqlUsername: ${{ parameters.sqlUsername }} # Required when authenticationType == Server
            sqlPassword: ${{ parameters.sqlPassword }} # Required when authenticationType == Server
            aadSqlUsername: ${{ parameters.aadSqlUsername }} # Required when authenticationType == AadAuthenticationPassword
            aadSqlPassword: ${{ parameters.aadSqlPassword }} # Required when authenticationType == AadAuthenticationPassword
            connectionString: ${{ parameters.connectionString }} # Required when authenticationType == ConnectionString
            deployType: 'DacpacTask'
            DeploymentAction: 'Publish'
            DacpacFile: '$(dacpacFilePath)'
            PublishProfile: '${{ parameters.publishProfile }}'
            AdditionalArguments: '${{ parameters.additionalArguments }}'
            IpDetectionMethod: 'AutoDetect'