parameters:
  buildConfiguration: 'Release'     # build configuration for build
  additionalArgs: ''                # additional msbuild args - default is specifying the output directory
  vsVersion: '15.0'                 # 15.0 = Visual Studio 2017. Other Options: 15.0 | 16.0 | Latest
  pool: 
    vmImage: 'windows-latest'

jobs:
- job: build_db
  displayName: Build Database
  pool: ${{ parameters.pool }}

  steps:

  - checkout: self

  - task: VSBuild@1
    displayName: VSBuild sqlproj
    inputs:
      solution: '**\*.sqlproj'
      vsVersion: '${{ parameters.vsVersion }}'
      configuration: '${{ parameters.buildConfiguration }}'
      msbuildArgs: '${{ parameters.additionalArgs }}'

  - task: CopyFiles@2
    inputs:
      Contents: '**/*.dacpac'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      flattenFolders: true

  - publish: '$(Build.ArtifactStagingDirectory)'
    artifact: drop-db
