parameters:
  environment: ''
  backendArg: ''
  azureSubscription: ''
  rootFolder: ''
  artifactName: 'plan'
  pool: 
    vmImage: 'ubuntu-latest'
jobs:
- deployment: destroy
  displayName: Terraform Destroy
  pool: ${{ parameters.pool }}
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - task: DownloadBuildArtifacts@0
          displayName: Download Plan
          inputs:
            buildType: current
            downloadType: single
            artifactName: ${{ parameters.artifactName }}
            downloadPath: '$(System.ArtifactsDirectory)'
        - template: get-tf-credentials.steps.yml
          parameters:
            azureSubscription: ${{ parameters.azureSubscription }}
        - script: |
            terraform init -no-color -input=false ${{ parameters.backendArg }}
            terraform destroy -no-color -input=false -auto-approve $(System.ArtifactsDirectory)/${{ parameters.artifactName }}/out.plan
          displayName: Terraform Destroy
          workingDirectory: ${{ parameters.rootFolder }}