parameters:
    imageRepository: ''
    dockerRegistryServiceConnection: ''
    tag: '$(Build.BuildId)'
    services: []
    pool: 
      vmImage: 'ubuntu-latest'
    
    
jobs:

- job: Build
  displayName: Build
  
  pool: ${{ parameters.pool }}
  steps: 

  # Kubernetes bake and manifest deploy - deploy the service if skip = false
  - ${{ each s in parameters.services }}:
    - ${{ if eq(s.skip, 'false') }}:

      - task: Docker@2
        displayName: Build ${{ s.serviceName }} and push image to container registry
        inputs:
          command: buildAndPush
          repository: ${{ s.imageRepository }}
          dockerfile: ${{ s.projectPath }}/Dockerfile
          containerRegistry: ${{ parameters.dockerRegistryServiceConnection }}
          tags: |
            ${{ parameters.tag }}

      - publish: ${{ s.projectPath }}/charts/${{ s.serviceName }}
        artifact: charts-${{ s.serviceName }}
        displayName: Publish charts-${{ s.serviceName }}