parameters:
    imageRepository: ''
    dockerfilePath: '**/Dockerfile'
    containerRegistry: ''
    dockerRegistryServiceConnection: ''
    tag: '$(Build.BuildId)'
    pool: 
      vmImage: 'ubuntu-latest'
    
    
jobs:
- job: build
  displayName: Docker build

  pool: ${{ parameters.pool }}

  steps:
  - task: Docker@2
    displayName: Build and push an image to container registry
    inputs:
      command: buildAndPush
      repository: ${{ parameters.imageRepository }}
      dockerfile: ${{ parameters.dockerfilePath }}
      containerRegistry: ${{ parameters.dockerRegistryServiceConnection }}
      tags: |
        ${{ parameters.tag }}
          
  - upload: manifests
    artifact: manifests