parameters:
  repoName: self

jobs:
- job: Build

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  #- checkout: ${{ parameters.repoName }}

  - script: |
      project.version=version=3.0.2-SNAPSHOT
      echo ${project.version}

  - task: MavenAuthenticate@0
    inputs:
      artifactsFeeds: 'Java-test'

  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'build'

  - publish: $(build.sourcesdirectory)
    artifact: drop