parameters:
  gradleTasks: 'clean publish'

jobs:
- job: Build

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: MavenAuthenticate@0
    inputs:
      artifactsFeeds: 'Java-test'

  - task: Gradle@2
    inputs:
      workingDirectory: ''
      options: '-PprojVersion=$(Build.BuildNumber)'
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: '${{ parameters.gradleTasks }}'

  - publish: $(build.sourcesdirectory)
    artifact: drop