parameters:
  repoName: self
  publishing.publications.myPlatform.version: 3.2.2
  project.version: ''
  project.parent.project.version: ''

jobs:
- job: Build

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  #- checkout: ${{ parameters.repoName }}

  - task: ReplaceTokens@1
    inputs:
      sourcePath: 
      filePattern: 'build.gradle'
      tokenRegex: '\${(\w+.\w+)}'

  - task: MavenAuthenticate@0
    inputs:
      artifactsFeeds: 'Java-test'

  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'build'

  - publish: $(build.sourcesdirectory)
    artifact: drop