parameters:
  project.version: ''
  project.parent.project.version: ''

jobs:
- job: Build

  pool:
    vmImage: 'ubuntu-latest'

  steps:

#  - task: ReplaceTokens@1
#    inputs:
#      sourcePath: 
#      filePattern: 'build.gradle'
#      tokenRegex: '\${(\w+.\w+.\w+.\w+)}'

  - task: MavenAuthenticate@0
    inputs:
      artifactsFeeds: 'Java-test'

  - task: Gradle@2
    inputs:
      workingDirectory: ''
      options: '-PprojVersion=$(Build.BuildNumber)'
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean build'

  - publish: $(build.sourcesdirectory)
    artifact: drop