trigger:
  - main
resources:
  repositories:
  - repository: templates
    type: github
    name: Devsec00ps/pipeline-templates
    endpoint: Devsec00ps

extends:
  template: secret-scanning-extends.yml
  parameters:
    buildStageName: build
    use steps template or job template for for build
    buildJobs:
    - template: sample-build-job.yml
      parameters:
        whatToBuild: 'Hello world'
    buildSteps:
    - template: sample-build-steps.yml
      parameters:
        whatToBuild: 'Hello world'
    deployStages:
    - stage: dev
      displayName: deploy to dev
      jobs: 
      # use deployment job template for deployment
      - template: sample-deployment-job.yml
        parameters:
          environment: github-secret-scanning-test-gate-dev
    - stage: prod
      displayName: deploy to prod
      jobs:
      - template: sample-deployment-job.yml
        parameters:
          environment: github-secret-scanning-test-gate-prod
