trigger:
  - main
  
# resources:
#   repositories:
#   - repository: templates
#     type: github
#     name: Devsec00ps/pipeline-templates
#     endpoint: Devsec00ps

extends:
  template: secret-scanning/secret-scanning-extends.yml
  parameters:
    buildStageName: build
    # use steps template or job template for for build
    buildJobs:
    - template: secret-scanning/sample-build-job.yml@templates
      parameters:
        whatToBuild: 'Hello world'
    # buildSteps:
    # - template: secret-scanning/sample-build-steps.yml@templates
    #   parameters:
    #     whatToBuild: 'Hello world'
    # deployStages:
    # - stage: dev
    #   displayName: deploy to dev
    #   jobs: 
    #   # use deployment job template for deployment
    #   - template: secret-scanning/sample-deployment-job.yml@templates
    #     parameters:
    #       environment: github-secret-scanning-test-gate-dev
    # - stage: prod
    #   displayName: deploy to prod
    #   jobs:
    #   - template: ../secret-scanning/sample-deployment-job.yml@templates
    #     parameters:
    #       environment: github-secret-scanning-test-gate-prod
