parameters:
  environment: ''
  pool: 
    vmImage: 'ubuntu-latest'
jobs:
- job: build
  displayName: build

  steps:
  - script: |
      echo "${{ parameters.whatToBuild }}, here is where I do my build!"