parameters:
  environment: 'Dev'
  services: []

jobs:

- ${{ each s in parameters.services }}:

  - deployment: 
    displayName: deploy ${{ s.name }}
    pool:
      vmImage: '${{ s.vmImage }}'

    environment: '${{ s.environment }}'

    strategy:
      runOnce:
        deploy:
          steps:

          # saves time only downloading the artifact needed
          - download: current
            artifact: ${{ s.name }}
        
          - task: ExtractFiles@1
            displayName: 'Extract files'
            inputs:
              archiveFilePatterns: '$(pipeline.workspace)/**/${{ s.name }}.zip'
              destinationFolder: '$(Pipeline.Workspace)/${{ s.name }}/deploy'

          - task: qetza.replacetokens.replacetokens-task.replacetokens@3
            displayName: 'Replace tokens'
            inputs:
              rootDirectory: '$(pipeline.workspace)'
              targetFiles: '${{ s.replaceTokensTargetFiles }}'
              escapeType: none
              verbosity: detailed

          # - task: qetza.replacetokens.replacetokens-task.replacetokens@3
          #   displayName: 'Replace tokens in .env'
          #   inputs:
          #     rootDirectory: '$(pipeline.workspace)'
          #     targetFiles: '**/Client/build/static/js/**.js'
          #     escapeType: none
          #     verbosity: detailed

          # Run any IIS deployment(s)
          - ${{ each i in s.iis }}:
            - task: IISWebAppDeploymentOnMachineGroup@0
              displayName: 'IIS Web App Deploy'
              condition: and(succeeded(), eq('${{ s.runDeploy }}', true))
              inputs:
                WebSiteName: '${{ i.websiteName }}'
                virtualApplication: '${{ i.virtualApplication }}'
                Package: '$(Pipeline.Workspace)/${{ s.name }}/deploy'
                RemoveAdditionalFilesFlag: true
                TakeAppOfflineFlag: true

          # Run any Azure deployment(s)
          - ${{ each az in s.azure }}:

            # Run any Azure Web App deployments
            - ${{ each azweb in az.webApp }}:
              - task: AzureRmWebAppDeployment@4
                displayName: 'Deploy Azure App Service'
                name: webAppDeployment
                condition: and(succeeded(), eq('${{ s.runDeploy }}', true))
                inputs:
                  azureSubscription: '${{ az.azureSubscription }}'
                  appType: 'webApp' # could make this a parameter if 'webAppLinux' was ever needed to be used
                  WebAppName: '${{ azweb.websiteName }}'
                  deployToSlotOrASE: true
                  ResourceGroupName: '${{ azweb.resourceGroupName }}'
                  SlotName: '${{ azweb.slotName }}'
                  packageForLinux: '$(Pipeline.Workspace)/${{ s.name }}/deploy'
                  AppSettings: '${{ s.appSettingsEdits }}'
                  JSONFiles: '${{ s.jsonVariableSubstituion }}'

              - task: AzureAppServiceManage@0
                inputs:
                  azureSubscription: '${{ az.azureSubscription }}'
                  Action: 'Swap Slots'
                  WebAppName: '${{ azweb.websiteName }}'
                  ResourceGroupName: '${{ azweb.resourceGroupName }}'
                  SourceSlot: '${{ azweb.slotName }}'
                  swapWithProduction: true

            # Run any Azure Function App deployments
            - ${{ each func in az.functionApp }}:
              - task: AzureFunctionApp@1
                inputs:
                  azureSubscription: '${{ az.azureSubscription }}'
                  appType: 'functionApp' # could make this a parameter if 'functionAppLinux' was ever needed to be used
                  appName: '${{ func.appName }}'
                  package: '$(Pipeline.Workspace)/${{ s.name }}/deploy'
                  deploymentMethod: 'auto'

            # Run any Azure APIM deployments
            - ${{ each api in az.apim }}:
              # sleep for 15 seconds to make sure the website is up and refreshed
              - pwsh: Start-Sleep -s 20
                displayName: Start-Sleep -s 20

              - task: stephane-eyskens.apim.apim.apim@3
                displayName: 'API Management - Create/Update API '
                inputs:
                  ConnectedServiceNameARM: '${{ api.apimAzureSubscription }}'
                  ResourceGroupName: '${{ api.resourceGroupName }}'
                  ApiPortalName: '${{ api.apiPortalName }}'
                  UseProductCreatedByPreviousTask: false
                  # product1: |
                  #   Starter
                  #   Unlimited
                  OpenAPISpec: v3
                  swaggerlocation: '$(webAppDeployment.AppServiceApplicationUrl)/swagger/v1/swagger.json'
                  targetapi: '${{ api.targetapi }}'
                  DisplayName: '${{ api.displayName }}'
                  pathapi: '${{ api.pathApi }}'
                  TemplateSelector: Custom
                  Custom: |
                    <policies>
                        <inbound>
                            <base />
                            <cors>
                                <allowed-origins>
                                    <origin>*</origin>
                                </allowed-origins>
                                <allowed-methods>
                                    <method>GET</method>
                                    <method>POST</method>
                                    <method>HEAD</method>
                                    <method>OPTIONS</method>
                                    <method>PATCH</method>
                                    <method>PUT</method>
                                    <method>DELETE</method>
                                    <method>TRACE</method>
                                </allowed-methods>
                                <allowed-headers>
                                    <header>*</header>
                                </allowed-headers>
                            </cors>
                            <set-backend-service base-url="$(webAppDeployment.AppServiceApplicationUrl)" />
                        </inbound>
                        <backend>
                            <base />
                        </backend>
                        <outbound>
                            <base />
                        </outbound>
                        <on-error>
                            <base />
                        </on-error>
                    </policies>
                  MicrosoftApiManagementAPIVersion: '2018-01-01'
